# Generated by Django 4.2.4 on 2023-09-05 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('map_type', models.CharField(max_length=100)),
                ('mount_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('mount_win', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OW_Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year_fall', models.IntegerField()),
                ('year_spring', models.IntegerField()),
                ('varsity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('ow_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.ow_team')),
            ],
        ),
        migrations.CreateModel(
            name='Push_Map',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=100)),
                ('mount_distance', models.IntegerField()),
                ('opponent_distance', models.IntegerField()),
                ('mount_tank', models.CharField(max_length=100)),
                ('mount_dps_1', models.CharField(max_length=100)),
                ('mount_dps_2', models.CharField(max_length=100)),
                ('mount_support_1', models.CharField(max_length=100)),
                ('mount_support_2', models.CharField(max_length=100)),
                ('opponent_tank', models.CharField(max_length=100)),
                ('opponent_dps_1', models.CharField(max_length=100)),
                ('opponent_dps_2', models.CharField(max_length=100)),
                ('opponent_support_1', models.CharField(max_length=100)),
                ('opponent_support_2', models.CharField(max_length=100)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('hero', models.CharField(max_length=100)),
                ('kills', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('damage', models.IntegerField(blank=True, null=True)),
                ('healing', models.IntegerField(blank=True, null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.game')),
                ('roster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.roster')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('match_type', models.CharField(max_length=100)),
                ('opponent', models.CharField(max_length=100)),
                ('mount_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('mount_win', models.BooleanField()),
                ('ow_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.ow_team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.match'),
        ),
        migrations.CreateModel(
            name='Flashpoint_Map',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=100)),
                ('point_number', models.IntegerField()),
                ('mount_percent', models.IntegerField()),
                ('opponent_percent', models.IntegerField()),
                ('mount_tank', models.CharField(max_length=100)),
                ('mount_dps_1', models.CharField(max_length=100)),
                ('mount_dps_2', models.CharField(max_length=100)),
                ('mount_support_1', models.CharField(max_length=100)),
                ('mount_support_2', models.CharField(max_length=100)),
                ('opponent_tank', models.CharField(max_length=100)),
                ('opponent_dps_1', models.CharField(max_length=100)),
                ('opponent_dps_2', models.CharField(max_length=100)),
                ('opponent_support_1', models.CharField(max_length=100)),
                ('opponent_support_2', models.CharField(max_length=100)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.game')),
            ],
        ),
        migrations.CreateModel(
            name='Escort_Hybrid_Map',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_Escort', models.BooleanField()),
                ('map_name', models.CharField(max_length=100)),
                ('attack_first', models.BooleanField()),
                ('mount_attack_tank', models.CharField(max_length=100)),
                ('mount_attack_dps_1', models.CharField(max_length=100)),
                ('mount_attack_dps_2', models.CharField(max_length=100)),
                ('mount_attack_support_1', models.CharField(max_length=100)),
                ('mount_attack_support_2', models.CharField(max_length=100)),
                ('opponent_defense_tank', models.CharField(max_length=100)),
                ('opponent_defense_dps_1', models.CharField(max_length=100)),
                ('opponent_defense_dps_2', models.CharField(max_length=100)),
                ('opponent_defense_support_1', models.CharField(max_length=100)),
                ('opponent_defense_support_2', models.CharField(max_length=100)),
                ('mount_defense_tank', models.CharField(max_length=100)),
                ('mount_defense_dps_1', models.CharField(max_length=100)),
                ('mount_defense_dps_2', models.CharField(max_length=100)),
                ('mount_defense_support_1', models.CharField(max_length=100)),
                ('mount_defense_support_2', models.CharField(max_length=100)),
                ('opponent_attack_tank', models.CharField(max_length=100)),
                ('opponent_attack_dps_1', models.CharField(max_length=100)),
                ('opponent_attack_dps_2', models.CharField(max_length=100)),
                ('opponent_attack_support_1', models.CharField(max_length=100)),
                ('opponent_attack_support_2', models.CharField(max_length=100)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.game')),
            ],
        ),
        migrations.CreateModel(
            name='Control_Map',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=100)),
                ('map_sub_name', models.CharField(max_length=100)),
                ('round', models.IntegerField()),
                ('mount_tank', models.CharField(max_length=100)),
                ('mount_dps_1', models.CharField(max_length=100)),
                ('mount_dps_2', models.CharField(max_length=100)),
                ('mount_support_1', models.CharField(max_length=100)),
                ('mount_support_2', models.CharField(max_length=100)),
                ('opponent_tank', models.CharField(max_length=100)),
                ('opponent_dps_1', models.CharField(max_length=100)),
                ('opponent_dps_2', models.CharField(max_length=100)),
                ('opponent_support_1', models.CharField(max_length=100)),
                ('opponent_support_2', models.CharField(max_length=100)),
                ('mount_percent', models.IntegerField()),
                ('opponent_percent', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.game')),
            ],
        ),
    ]
