# Generated by Django 4.2.4 on 2023-08-29 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('map_type', models.CharField(max_length=100)),
                ('mount_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('mount_win', models.BooleanField()),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mount_Comp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tank', models.CharField(max_length=100)),
                ('dps_1', models.CharField(max_length=100)),
                ('dps_2', models.CharField(max_length=100)),
                ('support_1', models.CharField(max_length=100)),
                ('support_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mount_Defence_Comp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tank', models.CharField(max_length=100)),
                ('dps_1', models.CharField(max_length=100)),
                ('dps_2', models.CharField(max_length=100)),
                ('support_1', models.CharField(max_length=100)),
                ('support_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opponent_Comp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tank', models.CharField(max_length=100)),
                ('dps_1', models.CharField(max_length=100)),
                ('dps_2', models.CharField(max_length=100)),
                ('support_1', models.CharField(max_length=100)),
                ('support_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opponent_Defence_Comp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tank', models.CharField(max_length=100)),
                ('dps_1', models.CharField(max_length=100)),
                ('dps_2', models.CharField(max_length=100)),
                ('support_1', models.CharField(max_length=100)),
                ('support_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OW_Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('varsity', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('ow_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.ow_team')),
            ],
        ),
        migrations.CreateModel(
            name='Push_Map',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=100)),
                ('mount_distance', models.IntegerField()),
                ('opponent_distance', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.game')),
                ('mount_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.mount_comp')),
                ('opponent_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.opponent_comp')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hero', models.CharField(max_length=100)),
                ('kills', models.IntegerField(null=True)),
                ('deaths', models.IntegerField(null=True)),
                ('assists', models.IntegerField(null=True)),
                ('damage', models.IntegerField(null=True)),
                ('healing', models.IntegerField(null=True)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.game')),
                ('roster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.roster')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('match_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
                ('mount_score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('mount_win', models.BooleanField()),
                ('ow_team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.ow_team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.match'),
        ),
        migrations.CreateModel(
            name='Flashpoint_Map',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=100)),
                ('point_number', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.game')),
                ('mount_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.mount_comp')),
                ('opponent_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.opponent_comp')),
            ],
        ),
        migrations.CreateModel(
            name='Escort_Hybrid_Map',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=100)),
                ('attack_first', models.BooleanField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.game')),
                ('mount_attack_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.mount_comp')),
                ('mount_defence_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.mount_defence_comp')),
                ('opponent_attack_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.opponent_comp')),
                ('opponent_defence_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.opponent_defence_comp')),
            ],
        ),
        migrations.CreateModel(
            name='Control_Map',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=100)),
                ('map_sub_name', models.CharField(max_length=100)),
                ('round', models.IntegerField()),
                ('mount_percent', models.IntegerField()),
                ('opponent_percent', models.IntegerField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.game')),
                ('mount_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.mount_comp')),
                ('opponent_comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.opponent_comp')),
            ],
        ),
    ]
