# Generated by Django 4.2.4 on 2023-08-30 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tank', models.CharField(max_length=100)),
                ('dps_1', models.CharField(max_length=100)),
                ('dps_2', models.CharField(max_length=100)),
                ('support_1', models.CharField(max_length=100)),
                ('support_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='control_map',
            name='mount_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_mount_comp', to='OverWatch_2.comp'),
        ),
        migrations.AlterField(
            model_name='control_map',
            name='opponent_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_opponent_comp', to='OverWatch_2.comp'),
        ),
        migrations.AlterField(
            model_name='escort_hybrid_map',
            name='mount_attack_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_payload_mount_attack_comp', to='OverWatch_2.comp'),
        ),
        migrations.AlterField(
            model_name='escort_hybrid_map',
            name='mount_defence_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_payload_mount_defence_comp', to='OverWatch_2.comp'),
        ),
        migrations.AlterField(
            model_name='escort_hybrid_map',
            name='opponent_attack_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_payload_opponent_attack_comp', to='OverWatch_2.comp'),
        ),
        migrations.AlterField(
            model_name='escort_hybrid_map',
            name='opponent_defence_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_payload_opponent_defence_comp', to='OverWatch_2.comp'),
        ),
        migrations.AlterField(
            model_name='flashpoint_map',
            name='mount_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashpoit_mount_comp', to='OverWatch_2.comp'),
        ),
        migrations.AlterField(
            model_name='flashpoint_map',
            name='opponent_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashpoint_opponent_comp', to='OverWatch_2.comp'),
        ),
        migrations.AlterField(
            model_name='push_map',
            name='mount_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_mount_comp', to='OverWatch_2.comp'),
        ),
        migrations.AlterField(
            model_name='push_map',
            name='opponent_comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_opponent_comp', to='OverWatch_2.comp'),
        ),
        migrations.DeleteModel(
            name='Mount_Comp',
        ),
        migrations.DeleteModel(
            name='Mount_Defence_Comp',
        ),
        migrations.DeleteModel(
            name='Opponent_Comp',
        ),
        migrations.DeleteModel(
            name='Opponent_Defence_Comp',
        ),
    ]
