# Generated by Django 4.2.4 on 2023-10-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0002_remove_player_game_id_player_control_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_defense',
            field=models.BooleanField(default=False),
        ),
    ]
