# Generated by Django 4.2.4 on 2023-08-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0002_comp_alter_control_map_mount_comp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ow_team',
            old_name='year',
            new_name='year_fall',
        ),
        migrations.AddField(
            model_name='ow_team',
            name='year_spring',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
    ]
