# Generated by Django 4.2.4 on 2023-08-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0003_rename_year_ow_team_year_fall_ow_team_year_spring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control_map',
            name='mount_comp',
        ),
        migrations.RemoveField(
            model_name='control_map',
            name='opponent_comp',
        ),
        migrations.RemoveField(
            model_name='escort_hybrid_map',
            name='mount_attack_comp',
        ),
        migrations.RemoveField(
            model_name='escort_hybrid_map',
            name='mount_defence_comp',
        ),
        migrations.RemoveField(
            model_name='escort_hybrid_map',
            name='opponent_attack_comp',
        ),
        migrations.RemoveField(
            model_name='escort_hybrid_map',
            name='opponent_defence_comp',
        ),
        migrations.RemoveField(
            model_name='flashpoint_map',
            name='mount_comp',
        ),
        migrations.RemoveField(
            model_name='flashpoint_map',
            name='opponent_comp',
        ),
        migrations.RemoveField(
            model_name='push_map',
            name='mount_comp',
        ),
        migrations.RemoveField(
            model_name='push_map',
            name='opponent_comp',
        ),
        migrations.AddField(
            model_name='control_map',
            name='mount_dps_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control_map',
            name='mount_dps_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control_map',
            name='mount_support_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control_map',
            name='mount_support_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control_map',
            name='mount_tank',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control_map',
            name='opponent_dps_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control_map',
            name='opponent_dps_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control_map',
            name='opponent_support_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control_map',
            name='opponent_support_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control_map',
            name='opponent_tank',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='mount_attack_dps_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='mount_attack_dps_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='mount_attack_support_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='mount_attack_support_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='mount_attack_tank',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='mount_defence_dps_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='mount_defence_dps_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='mount_defence_support_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='mount_defence_support_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='mount_defence_tank',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='opponent_attack_dps_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='opponent_attack_dps_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='opponent_attack_support_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='opponent_attack_support_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='opponent_attack_tank',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='opponent_defence_dps_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='opponent_defence_dps_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='opponent_defence_support_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='opponent_defence_support_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='opponent_defence_tank',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashpoint_map',
            name='mount_dps_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashpoint_map',
            name='mount_dps_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashpoint_map',
            name='mount_support_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashpoint_map',
            name='mount_support_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashpoint_map',
            name='mount_tank',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashpoint_map',
            name='opponent_dps_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashpoint_map',
            name='opponent_dps_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashpoint_map',
            name='opponent_support_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashpoint_map',
            name='opponent_support_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashpoint_map',
            name='opponent_tank',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='push_map',
            name='mount_dps_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='push_map',
            name='mount_dps_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='push_map',
            name='mount_support_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='push_map',
            name='mount_support_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='push_map',
            name='mount_tank',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='push_map',
            name='opponent_dps_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='push_map',
            name='opponent_dps_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='push_map',
            name='opponent_support_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='push_map',
            name='opponent_support_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='push_map',
            name='opponent_tank',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comp',
        ),
    ]
