# Generated by Django 4.2.4 on 2023-09-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0004_remove_control_map_mount_comp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
    ]
