# Generated by Django 4.2.4 on 2023-10-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0004_hero_map_sub_map_sub_map_image_map_image_hero_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map_image',
            name='map_id',
        ),
        migrations.RemoveField(
            model_name='sub_map_image',
            name='sub_map_id',
        ),
        migrations.AddField(
            model_name='hero',
            name='hero_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='map_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_map',
            name='sub_map_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Hero_Image',
        ),
        migrations.DeleteModel(
            name='Map_Image',
        ),
        migrations.DeleteModel(
            name='Sub_Map_Image',
        ),
    ]
