# Generated by Django 4.2.4 on 2023-09-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0005_remove_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='escort_hybrid_map',
            name='is_Escort',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
