# Generated by Django 4.2.4 on 2023-09-04 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0006_escort_hybrid_map_is_escort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='escort_hybrid_map',
            old_name='mount_defence_dps_1',
            new_name='mount_defense_dps_1',
        ),
        migrations.RenameField(
            model_name='escort_hybrid_map',
            old_name='mount_defence_dps_2',
            new_name='mount_defense_dps_2',
        ),
        migrations.RenameField(
            model_name='escort_hybrid_map',
            old_name='mount_defence_support_1',
            new_name='mount_defense_support_1',
        ),
        migrations.RenameField(
            model_name='escort_hybrid_map',
            old_name='mount_defence_support_2',
            new_name='mount_defense_support_2',
        ),
        migrations.RenameField(
            model_name='escort_hybrid_map',
            old_name='mount_defence_tank',
            new_name='mount_defense_tank',
        ),
        migrations.RenameField(
            model_name='escort_hybrid_map',
            old_name='opponent_defence_dps_1',
            new_name='opponent_defense_dps_1',
        ),
        migrations.RenameField(
            model_name='escort_hybrid_map',
            old_name='opponent_defence_dps_2',
            new_name='opponent_defense_dps_2',
        ),
        migrations.RenameField(
            model_name='escort_hybrid_map',
            old_name='opponent_defence_support_1',
            new_name='opponent_defense_support_1',
        ),
        migrations.RenameField(
            model_name='escort_hybrid_map',
            old_name='opponent_defence_support_2',
            new_name='opponent_defense_support_2',
        ),
        migrations.RenameField(
            model_name='escort_hybrid_map',
            old_name='opponent_defence_tank',
            new_name='opponent_defense_tank',
        ),
    ]
