# Generated by Django 4.2.4 on 2023-11-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0006_match_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_map',
            name='sub_map_image',
        ),
    ]
