# Generated by Django 4.2.4 on 2023-11-12 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0007_remove_sub_map_sub_map_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='control_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='OverWatch_2.control_map'),
        ),
        migrations.AlterField(
            model_name='player',
            name='escort_hybrid_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='OverWatch_2.escort_hybrid_map'),
        ),
        migrations.AlterField(
            model_name='player',
            name='flashpoint_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='OverWatch_2.flashpoint_map'),
        ),
        migrations.AlterField(
            model_name='player',
            name='push_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='OverWatch_2.push_map'),
        ),
    ]
