# Generated by Django 4.2.4 on 2023-09-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0007_rename_mount_defence_dps_1_escort_hybrid_map_mount_defense_dps_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
