# Generated by Django 4.2.4 on 2023-09-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0008_alter_game_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashpoint_map',
            name='mount_percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashpoint_map',
            name='opponent_percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
