# Generated by Django 4.2.4 on 2023-11-12 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0008_alter_player_control_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='control_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='control_players', to='OverWatch_2.control_map'),
        ),
        migrations.AlterField(
            model_name='player',
            name='escort_hybrid_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escort_hybrid_players', to='OverWatch_2.escort_hybrid_map'),
        ),
        migrations.AlterField(
            model_name='player',
            name='flashpoint_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashpoint_players', to='OverWatch_2.flashpoint_map'),
        ),
        migrations.AlterField(
            model_name='player',
            name='push_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_players', to='OverWatch_2.push_map'),
        ),
    ]
