# Generated by Django 4.2.4 on 2023-12-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0009_alter_player_control_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map_Type',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('map_type', models.CharField(max_length=100)),
            ],
        ),
    ]
