# Generated by Django 4.2.4 on 2023-09-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0010_player_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='damage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='deaths',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='healing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='kills',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
