# Generated by Django 4.2.4 on 2023-12-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0010_map_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.DateField(default='2023-12-28'),
            preserve_default=False,
        ),
    ]
