# Generated by Django 4.2.4 on 2024-01-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0011_match_match_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map_Type',
        ),
        migrations.AddField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
