# Generated by Django 4.2.4 on 2024-01-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0012_delete_map_type_player_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_active',
        ),
        migrations.AddField(
            model_name='roster',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
