# Generated by Django 4.2.4 on 2024-01-25 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0013_remove_player_is_active_roster_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clash_Map',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('map_name', models.CharField(max_length=100)),
                ('mount_tank', models.CharField(max_length=100)),
                ('mount_dps_1', models.CharField(max_length=100)),
                ('mount_dps_2', models.CharField(max_length=100)),
                ('mount_support_1', models.CharField(max_length=100)),
                ('mount_support_2', models.CharField(max_length=100)),
                ('opponent_tank', models.CharField(max_length=100)),
                ('opponent_dps_1', models.CharField(max_length=100)),
                ('opponent_dps_2', models.CharField(max_length=100)),
                ('opponent_support_1', models.CharField(max_length=100)),
                ('opponent_support_2', models.CharField(max_length=100)),
                ('A_point_win', models.BooleanField()),
                ('B_point_win', models.BooleanField()),
                ('C_point_win', models.BooleanField()),
                ('D_point_win', models.BooleanField()),
                ('E_point_win', models.BooleanField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OverWatch_2.game')),
            ],
        ),
    ]
