# Generated by Django 4.2.4 on 2024-01-26 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0014_clash_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clash_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clash_players', to='OverWatch_2.clash_map'),
        ),
    ]
