# Generated by Django 4.2.4 on 2024-01-26 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0015_player_clash_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clash_Map',
            new_name='ClashMap',
        ),
        migrations.RenameModel(
            old_name='Control_Map',
            new_name='ControlMap',
        ),
        migrations.RenameModel(
            old_name='Escort_Hybrid_Map',
            new_name='EscortHybridMap',
        ),
        migrations.RenameModel(
            old_name='Flashpoint_Map',
            new_name='FlashpointMap',
        ),
        migrations.RenameModel(
            old_name='Match_Type',
            new_name='MatchType',
        ),
        migrations.RenameModel(
            old_name='OW_Team',
            new_name='OwTeam',
        ),
        migrations.RenameModel(
            old_name='Push_Map',
            new_name='PushMap',
        ),
        migrations.RenameModel(
            old_name='Sub_Map',
            new_name='SubMap',
        ),
    ]
