# Generated by Django 4.2.4 on 2024-01-26 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0016_rename_clash_map_clashmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clashmap',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clash_map_set', to='OverWatch_2.game'),
        ),
    ]
