# Generated by Django 4.2.4 on 2024-01-26 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0017_alter_clashmap_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlmap',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_map_set', to='OverWatch_2.game'),
        ),
        migrations.AlterField(
            model_name='escorthybridmap',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escort_hybrid_map_set', to='OverWatch_2.game'),
        ),
        migrations.AlterField(
            model_name='flashpointmap',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashpoint_map_set', to='OverWatch_2.game'),
        ),
        migrations.AlterField(
            model_name='pushmap',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_map_set', to='OverWatch_2.game'),
        ),
    ]
