# Generated by Django 4.2.4 on 2024-01-26 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OverWatch_2', '0018_alter_controlmap_game_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submap',
            name='map_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_map_set', to='OverWatch_2.map'),
        ),
    ]
